/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "system_stm32f4xx.h"
#include "stm32f401re.h"
#include "stm32f401re_rcc.h"
#include "stm32f401re_gpio.h"
#include "stm32f401re_usart.h"
#include "misc.h"

#include "eventman.h"
#include "timer.h"
#include "led.h"
#include "melody.h"
#include "lightsensor.h"
#include "temhumsensor.h"
#include "eventbutton.h"
#include "button.h"
#include "Ucglib.h"
#include "uartcmd.h"
#include "serial.h"

#include "stm32f401re_i2c.h"


#define USART1_TX_GPIO_PIN       GPIO_Pin_6
#define USART1_RX_GPIO_PIN       GPIO_Pin_7

#define USART1_GPIO_PORT      GPIOB
#define USART1_GPIO_CLOCK     RCC_AHB1Periph_GPIOB
#define USART1_CLOCK          RCC_APB2Periph_USART1

#define GPIO_PIN_SET          1
#define GPIO_PIN_RESET        0



#define BUZZER_GPIO_PORT       GPIOC
#define BUZZER_GPIO_PIN        GPIO_Pin_9
#define BUZZER_GPIO_RCC        RCC_AHB1Periph_GPIOC

//Led board PA5
#define LED_GPIO_PORT_BOARD       GPIOA
#define LED_GPIO_PIN_BOARD        GPIO_Pin_5
#define LED_GPIO_RCC_BOARD        RCC_AHB1Periph_GPIOA

//Led 2
#define LED_GPIO_PORT_2_RED       GPIOA
#define LED_GPIO_PIN_2_RED        GPIO_Pin_1
#define LED_GPIO_RCC_2_RED      RCC_AHB1Periph_GPIOA

#define LED_GPIO_PORT_2_BLUE       GPIOC
#define LED_GPIO_PIN_2_BLUE        GPIO_Pin_8
#define LED_GPIO_RCC_2_BLUE      RCC_AHB1Periph_GPIOC

#define LED_GPIO_PORT_2_GREEN       GPIOA
#define LED_GPIO_PIN_2_GREEN        GPIO_Pin_0
#define LED_GPIO_RCC_2_GREEN      RCC_AHB1Periph_GPIOA

//Led 1
#define LED_GPIO_PORT_1_RED       GPIOB
#define LED_GPIO_PIN_1_RED        GPIO_Pin_13
#define LED_GPIO_RCC_1_RED      RCC_AHB1Periph_GPIOB

#define LED_GPIO_PORT_1_BLUE       GPIOA
#define LED_GPIO_PIN_1_BLUE        GPIO_Pin_10
#define LED_GPIO_RCC_1_BLUE      RCC_AHB1Periph_GPIOA

#define LED_GPIO_PORT_1_GREEN      GPIOA
#define LED_GPIO_PIN_1_GREEN        GPIO_Pin_11
#define LED_GPIO_RCC_1_GREEN      RCC_AHB1Periph_GPIOA

//Led Id
typedef enum
{
    LED_BOARD = 0,   /* LED on-board (PA5) */
    LED_1_BLUE,
	LED_1_RED,
	LED_1_GREEN,
    LED_2_BLUE,
    LED_2_RED,
    LED_2_GREEN,
} Led_Id_t;



static uint8_t count=0;

static uint8_t byRxData;

// Buffer chứa dữ liệu của frame đã nhận
uint8_t by_RxBuffer[RX_BUFFER_SIZE]={0};

static ucg_t ucg;
static char src1[20] = "";

void Delay_ms(uint32_t milisecond)
{
	for (uint32_t i = 0; i < milisecond; i++)
	{
		for (uint32_t j = 0; j < 5000; j++);
	}
}


static void Led_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;

    //Enable Clock
    RCC_AHB1PeriphClockCmd(
            LED_GPIO_RCC_BOARD |
            LED_GPIO_RCC_1_RED | LED_GPIO_RCC_1_BLUE | LED_GPIO_RCC_1_GREEN |
            LED_GPIO_RCC_2_RED | LED_GPIO_RCC_2_BLUE | LED_GPIO_RCC_2_GREEN,
            ENABLE
        );
    //Cấu hình cho GPIO chung
    GPIO_InitStructure.GPIO_Mode  = GPIO_Mode_OUT;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
    GPIO_InitStructure.GPIO_PuPd  = GPIO_PuPd_NOPULL;

    /* ================= LED RGB 1 ================= */
    GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN_1_RED;
    GPIO_Init(LED_GPIO_PORT_1_RED, &GPIO_InitStructure);

    GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN_1_BLUE;
    GPIO_Init(LED_GPIO_PORT_1_BLUE, &GPIO_InitStructure);

    GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN_1_GREEN;
    GPIO_Init(LED_GPIO_PORT_1_GREEN, &GPIO_InitStructure);
    /* ================= LED RGB 2 ================= */

    /* RED – GPIOB */
    GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN_2_RED;
    GPIO_Init(LED_GPIO_PORT_2_RED, &GPIO_InitStructure);

    GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN_2_BLUE;
    GPIO_Init(LED_GPIO_PORT_2_BLUE, &GPIO_InitStructure);

    GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN_2_GREEN;
    GPIO_Init(LED_GPIO_PORT_2_GREEN, &GPIO_InitStructure);
}


static void Led_Control(uint8_t led_id, uint8_t led_state)
{
	GPIO_TypeDef* GPIOx;
	uint16_t GPIO_Pin;
	/* Chọn GPIO & Pin tương ứng với LED */
	switch (led_id)
	    {
	        /* ========= LED ON BOARD ========= */
	        case LED_BOARD:
	            GPIOx = LED_GPIO_PORT_BOARD;
	            GPIO_Pin = LED_GPIO_PIN_BOARD;
	            break;

	        /* ========= LED RGB 1 ========= */
	        case LED_1_RED:
	            GPIOx = LED_GPIO_PORT_1_RED;
	            GPIO_Pin = LED_GPIO_PIN_1_RED;
	            break;

	        case LED_1_GREEN:
	            GPIOx = LED_GPIO_PORT_1_GREEN;
	            GPIO_Pin = LED_GPIO_PIN_1_GREEN;
	            break;

	        case LED_1_BLUE:
	            GPIOx = LED_GPIO_PORT_1_BLUE;
	            GPIO_Pin = LED_GPIO_PIN_1_BLUE;
	            break;

	        /* ========= LED RGB 2 ========= */
	        case LED_2_RED:
	            GPIOx = LED_GPIO_PORT_2_RED;
	            GPIO_Pin = LED_GPIO_PIN_2_RED;
	            break;

	        case LED_2_GREEN:
	            GPIOx = LED_GPIO_PORT_2_GREEN;
	            GPIO_Pin = LED_GPIO_PIN_2_GREEN;
	            break;

	        case LED_2_BLUE:
	            GPIOx = LED_GPIO_PORT_2_BLUE;
	            GPIO_Pin = LED_GPIO_PIN_2_BLUE;
	            break;

	        default:
	            return;
	    }

	//Bật/Tắt Led
	if (led_state== GPIO_PIN_SET)
	{
		GPIO_SetBits(GPIOx, GPIO_Pin);
	}
	else if (led_state == GPIO_PIN_RESET)
	    {
	        GPIO_ResetBits(GPIOx, GPIO_Pin);
	    }
}

/* Danh sách các LED sẽ xoay vòng — có thể mở rộng */
static const Led_Id_t led_color_list[] = { LED_1_BLUE, LED_1_RED, LED_1_GREEN };
#define LED_COLOR_COUNT  (sizeof(led_color_list) / sizeof(led_color_list[0]))

static uint8_t led_color_idx = 0;   // chỉ số trong mảng trên

/* Trả về LED_id hiện tại */
static Led_Id_t getCurrentLed(void)
{
    return led_color_list[led_color_idx];
}

/* Tắt tất cả LED RGB 1 (dùng khi đổi màu) */
static void Led_AllOff(void)
{
    Led_Control(LED_1_RED,   GPIO_PIN_RESET);
    Led_Control(LED_1_GREEN, GPIO_PIN_RESET);
    Led_Control(LED_1_BLUE,  GPIO_PIN_RESET);
}

/* Đổi sang màu kế tiếp */
static void changeLED(void)
{
    Led_AllOff();                                              // tắt LED cũ
    led_color_idx = (led_color_idx + 1) % LED_COLOR_COUNT;     // xoay vòng
    if (count > 0) {
        Led_Control(getCurrentLed(), GPIO_PIN_SET);
    }
}

static void Buzzer_Init(void)
{
    /* Declare type variable GPIO Structure */
    GPIO_InitTypeDef GPIO_InitStructure;

    /* Enable Clock GPIOA */
    RCC_AHB1PeriphClockCmd(BUZZER_GPIO_RCC, ENABLE);

    /* Choose Pin Buzzer */
    GPIO_InitStructure.GPIO_Pin = BUZZER_GPIO_PIN;

    /* Choose Pin Led as Out */
    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;

    /* Choose Speed Pin */
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

    /* Select type */
    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

    /* The function initializes all of the above values */
    GPIO_Init(BUZZER_GPIO_PORT, &GPIO_InitStructure);
}

static void Buzzer_Control(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint8_t status)
{
    /* Set bit in BSRR Registers */
    if (status == GPIO_PIN_SET)
    {
        GPIO_SetBits(GPIOx, GPIO_Pin);
    }
    /* Reset bit in BSRR Registers */
    else if (status == GPIO_PIN_RESET)
    {
        GPIO_ResetBits(GPIOx, GPIO_Pin);
    }
}



volatile uint8_t Data_Receive;

void USART1_Init(void)
{
	GPIO_InitTypeDef  GPIO_InitStructure;
	USART_InitTypeDef  USART_InitStructure;
	NVIC_InitTypeDef  NVIC_InitStructure;

    RCC_AHB1PeriphClockCmd(USART1_GPIO_CLOCK, ENABLE);

    GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
    GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
    GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
    GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;

    GPIO_InitStructure.GPIO_Pin = USART1_TX_GPIO_PIN | USART1_RX_GPIO_PIN;
    GPIO_Init(USART1_GPIO_PORT, &GPIO_InitStructure);

    GPIO_PinAFConfig(USART1_GPIO_PORT, GPIO_PinSource6, GPIO_AF_USART1);
    GPIO_PinAFConfig(USART1_GPIO_PORT, GPIO_PinSource7, GPIO_AF_USART1);


    RCC_APB2PeriphClockCmd(USART1_CLOCK, ENABLE);
    USART_InitStructure.USART_BaudRate = 115200;
    USART_InitStructure.USART_WordLength = USART_WordLength_8b;
    USART_InitStructure.USART_StopBits = USART_StopBits_1;
    USART_InitStructure.USART_Parity = USART_Parity_No;
    USART_InitStructure.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
    USART_InitStructure.USART_Mode = USART_Mode_Rx | USART_Mode_Tx;

    USART_Init(USART1, &USART_InitStructure);
    USART_Cmd(USART1, ENABLE);

    USART_ITConfig(USART1, USART_IT_RXNE, ENABLE);

    NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);

    NVIC_InitStructure.NVIC_IRQChannel = USART1_IRQn;
    NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0;
    NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
    NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;

    NVIC_Init(&NVIC_InitStructure);
}




static buffqueue_t serialQueueRx;   // Cấu trúc FIFO
static uint8_t pBuffDataRx[256]; // vùng nhớ FIFO
static uint8_t buzzertoggle = 0;

void USART1_IRQHandler(void)
{
	if (USART_GetITStatus(USART1, USART_IT_RXNE) == SET)
	{
		uint8_t data = (uint8_t)USART_ReceiveData(USART1);
		bufEnDat(&serialQueueRx, &data);
		buzzertoggle = 1;

	}
	USART_ClearITPendingBit(USART1, USART_IT_RXNE);
}


void SerialInit(void)
{
    bufInit(pBuffDataRx, &serialQueueRx, sizeof(pBuffDataRx[0]), 256);
    USART1_Init();
}



void process_SerialReceiver(void)
{

    uint8_t byRxData;
    while (bufNumItems(&serialQueueRx) > 0)
    {
        bufDeDat(&serialQueueRx, &byRxData);

        /* Sentinel value 0xFF = đổi màu LED */
        if (byRxData == 0xFF) {
            changeLED();
            continue;
        }

        /* Còn lại là count */
        uint8_t count = byRxData;

            sprintf(src1, "So nguoi: %d   ", count);
            ucg_DrawString(&ucg, 10, 42, 0, src1);

            /* Cập nhật LED */
            if (count > 0) {
                Led_AllOff();
                Led_Control(getCurrentLed(), GPIO_PIN_SET);
            } else {
                Led_AllOff();
            }

    }
}




int main(void)
{
	SystemCoreClockUpdate();
	SerialInit();
	Led_Init();
	Buzzer_Init();

	TimerInit();

	// Khởi tạo màn hình LCD
    Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
    ucg_ClearScreen(&ucg);
    ucg_SetFont(&ucg, ucg_font_ncenR10_hr); // font chữ
    ucg_SetColor(&ucg, 0, 255, 255, 255);   // màu chữ trắng
    ucg_SetColor(&ucg, 1, 0, 0, 0);         // nền đen
    ucg_SetRotate180(&ucg);                 // xoay 180 độ

    ucg_DrawString(&ucg, 0, 14, 0, "System Ready");

    sprintf(src1, "So nguoi: %d   ", count);
    ucg_DrawString(&ucg, 10, 42, 0, src1);

    while(1)
    {
    	processTimerScheduler();
    	process_SerialReceiver();
    	if(buzzertoggle == 1)
    	{
    		Buzzer_Control(BUZZER_GPIO_PORT, BUZZER_GPIO_PIN, 1);
    		Delay_ms(100);
    		Buzzer_Control(BUZZER_GPIO_PORT, BUZZER_GPIO_PIN, 0);
    		buzzertoggle=0;

    	}
    }
}

